### ISSUE TITLE
Symlinks shouldn't be unrolled

### ISSUE THREAD

**Issue by marcello3d** [jlevy/instaclone#4]
Due to how npm creates the `node_modules/.bin` folder, unrolling symlinks breaks all `node_modules/.bin`.

Probably best to just preserve symlinks?

**Comment by jlevy** [comment]
Candidate plan:
- Migrate to .tar.gz and include symlinks
- Preserve symlinks that resolve to within node_modules
- Either fail or unroll symlinks that resolve to absolute paths and/or outside node_modules (perhaps depending on flag?)
